// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/CopyUrl.tsx";
import * as $$1 from "./islands/Entry.tsx";
import * as $$2 from "./islands/TextArea.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/CopyUrl.tsx": $$0,
    "./islands/Entry.tsx": $$1,
    "./islands/TextArea.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
